export const games = [
  { name: "12 Mini Battles", img: "images/12 mini battles.jpg", link: "g/12 Mini Battles.html" },
  { name: "1v1.lol", img: "images/1v1 lol.png", link: "g/1v1.LoL.html" },
  { name: "2048", img: "images/2048.png", link: "g/2048.html" },
  { name: "8 Ball Pool", img: "images/8 ball pool.png", link: "g/8 Ball Pool.html" },
  { name: "A Bite at Freddy's", img: "images/a bite at freddy's.webp", link: "g/A Bite at Freddy's.html" },
  { name: "A Dance of Fire and Ice", img: "images/a dance of fire and ice.jpg", link: "g/A Dance of Fire and Ice.html" },
  { name: "A Difficult Game About Climbing", img: "images/a difficult game about climbing.webp", link: "g/A Difficult Game About Climbing.html" },
  { name: "A Small World Cup", img: "images/asmallworldcup-min.jpg", link: "g/A Small World Cup.html" },
  { name: "Abandoned", img: "images/abandoned.png", link: "g/Abandoned.html" },
  { name: "Amanda the Adventurer", img: "images/amanda the adventurer.webp", link: "g/Amanda the Adventurer.html" },
  { name: "Amaze", img: "images/amaze.webp", link: "g/Amaze.html" },
  { name: "Andy's Apple Farm", img: "images/AAF.jpg", link: "g/Andy's Apple Farm.html" },
  { name: "Angry Birds", img: "images/angry birds.png", link: "g/Angry Birds.html" },
  { name: "BitLife", img: "images/blife.webp", link: "g/B1tLife.html" },
  { name: "BLOODMONEY", img: "images/bloodmoney.webp", link: "g/BLOODMONEY!.html" },
  { name: "Bad Parenting", img: "images/BpTB.webp", link: "g/Bad Parenting 1.html" },
  { name: "Bad Time Simulator", img: "images/bad time simulator.png", link: "g/Bad Time Simulator.html" },
  { name: "Baldi's Basics Classic Remastered", img: "images/BaldisBasicsPlus.webp", link: "g/Baldi's Basics Classic Remastered.html" },
  { name: "Baldi's Basics", img: "images/BaldisBasicsPlus.webp", link: "g/Baldi's Basics.html" },
  { name: "Baldi's Basics Plus", img: "images/BaldisBasicsPlus.webp", link: "g/BaldisBasicsPlus.html" },
  { name: "Bank Robbery 2", img: "images/bank robbery 2.png", link: "g/Bank Robbery 2.html" },
  { name: "Basket Battle", img: "images/basketbattles.png", link: "g/Basket Battle.html" },
  { name: "Basketball Stars", img: "images/basketbattles.png", link: "g/Basketball Stars.html" },
  { name: "Bendy and the Ink Machine", img: "images/Bendy.jpg", link: "g/Bendy and the Ink Machine.html" },
  { name: "Binding of Issac: Wrath of the Lamb", img: "images/binding of issac.png", link: "g/Binding of Issac_ Wrath of the Lamb.html" },
  { name: "Block Blast", img: "images/block blast.webp", link: "g/Block Blast.html" },
  { name: "Bow Masters", img: "images/bowmaster.webp", link: "g/Bow Masters.html" },
  { name: "Bridge Race", img: "images/bridge race.webp", link: "g/Bridge Race.html" },
  { name: "Buckshot Roulette", img: "images/buckshot roulette.png", link: "g/Buckshot" },
  { name: "Celeste", img: "images/celeste.png", link: "g/Celeste.html" },
  { name: "Chat Bot", img: "images/chat bot.jpg", link: "g/Chat Bot (A._.I).html" },
  { name: "CircleO", img: "images/circleo.png", link: "g/CircleO.html" },
  { name: "City Smash", img: "images/city smash.png", link: "g/City Smash.html" },
  { name: "Color Water Sort 3D", img: "images/color water sort 3d.png", link: "g/Color Water Sort 3D.html" },
  { name: "Cookie Clicker", img: "images/cookie clicker.webp", link: "g/Cookie Clicker.html" },
  { name: "Crazy Cars", img: "images/crazy-cars.jpg", link: "g/Crazy Cars.html" },
  { name: "Crossy Road", img: "images/crossy road.webp", link: "g/Crossy Road.html" },
  { name: "Cuphead", img: "images/cuphead.jpg", link: "g/Cuphead.html" },
  { name: "Cut the Rope", img: "images/cut the rope.png", link: "g/Cut the Rope.html" },
  { name: "Deltarune", img: "images/deltarune.webp", link: "g/Deltarune.html" },
  { name: "Deltarune Chapter 2", img: "images/deltarune.webp", link: "g/Deltarune Chapter 2.html" },
  { name: "Deltarune Chapter 3", img: "images/deltarune.webp", link: "g/Deltarune Chapter 3.html" },
  { name: "Deltarune Chapter 4", img: "images/deltarune.webp", link: "g/Deltarune Chapter 4.html" },
  { name: "Deltatraveler", img: "images/deltatraveler.png", link: "g/Deltatraveler.html" },
  { name: "Doge Miner", img: "images/doge miner.png", link: "g/Doge Miner.html" },
  { name: "Doge Miner 2", img: "images/doge miner.png", link: "g/Dogeminer 2.html" },
  { name: "Draw the Line", img: "images/draw the line.png", link: "g/Draw the Line.html" },
  { name: "DrawJoust", img: "images/Draw Joust.png", link: "g/Drawjoust.html" },
  { name: "Endoparasitic", img: "images/endoparasitic.png", link: "g/Endoparasitic.html" },
  { name: "Five Nights at Freddy's", img: "images/fnaf1.png", link: "g/Five Nights at Freddy's.html" },
  { name: "Five Nights at Freddy's 2", img: "images/fnaf2.png", link: "g/Five Nights at Freddy's 2.html" },
  { name: "Five Nights at Freddy's 3", img: "images/fnaf3.png", link: "g/Five Nights at Freddy's 3.html" },
  { name: "Five Nights at Freddy's 4", img: "images/fnaf4.png", link: "g/Five Nights at Freddy's 4.html" },
  { name: "Five Nights at Freddy's: Ultimate Custom Night", img: "images/fnaf ucn.png", link: "g/Five Nights at Freddy's_ Ultimate Custom Night.html" },
  { name: "Five Nights at Freddy's: World", img: "images/fnaf world.png", link: "g/Five Nights at Freddy's_ World" },
  { name: "Five Nights at Freddy's: Pizza Simulator", img: "images/fnaf pizza simulator.png", link: "g/Five Nights at Freddy's_ Pizza Simulator.html" },
  { name: "Five Nights at Freddy's: Sister Location", img: "images/fnaf sister location.png", link: "g/Five Nights at Freddy's_ Sister Location.html" },
  { name: "FNF VS IMPOSTER V4", img: "images/FNFVSIMPOSTERV4.jpg", link: "g/Friday Night Funkin VS Impostor v4.html" },
  { name: "FNF VS Sky", img: "images/fnf vs sky.png", link: "g/Friday Night Funkin VS. Sky.html" },
  { name: "FNF VS Nonsense", img: "images/fnf nonsense.jpg", link: "g/Friday Night Funkin vs Nonsense.html" },
  { name: "FNF VS Hit Single Real", img: "images/HitSingleReal.png", link: "g/Friday Night Funkin'_ Hit Single Real.html" },
  { name: "FNF VS Indie Cross", img: "images/indie cross.webp", link: "g/Friday Night Funkin'_ Indie Cross.html" },
  { name: "FNF VS Mid Fight Mass", img: "images/mid fight mass.webp", link: "g/Friday Night Funkin'_ Sarvente's Mid-Fight Masses.html" },
  { name: "FNF VS Sonic Legacy", img: "images/fnf vs sonic legacy.png", link: "g/Friday Night Funkin'_ Sonic Legacy.html" },
  { name: "FNF VS Whitty", img: "images/fnf whitty.webp", link: "g/Friday Night Funkin'_ V.S. Whitty.html" },
  { name: "FNF VS Hex", img: "images/hex.jpg", link: "g/Friday Night Funkin'_ Vs. Hex.html" },
  { name: "FNF VS Garcello", img: "images/fnf garcello.jpg", link: "g/Friday Night Funkin'_ vs. Garcello.html" },
  { name: "FNF VS QT", img: "images/qt FNF.webp", link: "g/Friday Night Funkin'_ vs. QT.html" },
  { name: "FNF VS Tricky", img: "images/Tricky.jpg", link: "g/Friday Night Funkin'_ vs. Tricky.html" },
  { name: "FNF VS Undertale", img: "images/fnf vs undertale.png", link: "g/FNF VS Undertale.html" },
  { name: "Friday Night Funkin'", img: "images/FNF.webp", link: "g/Friday Night Funkin.html" },
  { name: "Geometry Dash Lite", img: "images/geometry dash lite.webp", link: "g/Geometry Dash Lite.html" },
  { name: "Getting Over It", img: "images/GettingOverIt.webp", link: "g/Getting Over It with Bennett Foddy.html" },
  { name: "Google Fued", img: "images/GoogleFued.jpg", link: "g/Google Fued.html" },
  { name: "Gorilla Tag", img: "images/gorillatag.png", link: "g/Gorilla Tag.html" },
  { name: "Granny", img: "images/granny.webp", link: "g/Granny.html" },
  { name: "Granny 2", img: "images/granny.webp", link: "g/Granny 2.html" },
  { name: "Granny 3", img: "images/granny.webp", link: "g/Granny 3.html" },
  { name: "Granny 4", img: "images/granny.webp", link: "g/Granny 4.html" },
  { name: "Gun Spin", img: "images/gunspin.png", link: "g/Gun Spin.html" },
  { name: "Henry Stickman: Breaking the Bank", img: "images/henry stickman.webp", link: "g/Breaking the Bank.html" },
  { name: "Henry Stickman: Escaping the Prison", img: "images/henry stickman.webp", link: "g/Escaping the Prison.html" },  
  { name: "Henry Stickman: Stealing the Diamond", img: "images/henry stickman.webp", link: "g/Stealing the Diamond.html" },
  { name: "Henry Stickman: Infiltraing the Airship", img: "images/henry stickman.webp", link: "g/Infiltraing the Airship.html" },
  { name: "Henry Stickman: Fleeing the Complex", img: "images/henry stickman.webp", link: "g/Fleeing the Complex.html" },
  { name: "Happy Wheels", img: "images/happy wheels.webp", link: "g/Happy Wheels.html" },
  { name: "Hill Climb Racing Lite", img: "images/hill climb racing.webp", link: "g/Hill Climb Racing Lite.html" },
  { name: "Hollow Knight", img: "images/HallowNight.jpg", link: "g/Hollow Knight.html" },
  { name: "Human Expenditure Program", img: "images/human expenditure program.png", link: "g/Human Expenditure Program.html" },
  { name: "Jelly Drift", img: "images/jelly drift.png", link: "g/Jelly Drift.html" },
  { name: "Karlson", img: "images/karlson.png", link: "g/Karlson.html" },
  { name: "Kindergarden", img: "images/Kindergarden.jpg", link: "g/Kindergarten.html" },
  { name: "Kindergarden 2", img: "images/Kindergarden2.jpg", link: "g/Kindergarten 2.html" },
  { name: "Kindergarden 3", img: "images/Kindergarden3.webp", link: "g/Kindergarten 3.html" },
  { name: "Lama Loop", img: "images/lama loop.webp", link: "g/Lama Loop.html" },
  { name: "Learn to fly", img: "images/LearnToFly.jpg", link: "g/Learn to Fly.html" },
  { name: "Learn to fly 2", img: "images/LearnToFly2.jpg", link: "g/Learn to Fly 2.html" },
  { name: "Learn to fly 3", img: "images/LearnToFly3.png", link: "g/Learn to Fly 3.html" },
  { name: "Little Runmo", img: "images/little runmo.png", link: "g/Little Runmo.html" },
  { name: "Magic Tiles 3", img: "images/magic tiles 3.png", link: "g/Magic Tiles 3.html" },
  { name: "Melon Playground", img: "images/melon playground.webp", link: "g/Melon Playground.html" },
  { name: "Midnight Shift", img: "images/midnight shift.png", link: "g/Midnight Shift.html" },
  { name: "Minecraft 1.12.2", img: "images/mc.png", link: "g/Minecraft 1.12.2.html" },
  { name: "Minecraft 1.21.4", img: "images/mc.png", link: "g/Minecraft 1.21.4.html" },
  { name: "Minesweeper Mania", img: "images/minesweeper mania.png", link: "g/Minesweeper Mania.html" },
  { name: "Moto X3M", img: "images/motoxm.jpg", link: "g/Moto X3M.html" },
  { name: "Moto X3M 2", img: "images/motoxm2.jpg", link: "g/Moto X3M 2.html" },
  { name: "Moto X3M 3", img: "images/motoxm3.webp", link: "g/Moto X3M 3.html" },
  { name: "Moto X3M Pool Party", img: "images/motoxmpoolparty.webp", link: "g/Moto X3M Pool Party.html" },
  { name: "Moto X3M Winter", img: "images/motoxmwinter.jpg", link: "g/Moto X3M Winter.html" },
  { name: "Moto X3M Spooky", img: "images/motoxmspooky.png", link: "g/Moto X3M Spooky.html" },
  { name: "Oneshot (LEGACY)", img: "images/oneshot.png", link: "g/Oneshot Legacy.html" },
  { name: "OvO", img: "images/ovo.webp", link: "g/OvO.html" },
  { name: "OvO 2", img: "images/ovo2.webp", link: "g/OvO 2.html" },
  { name: "OvO 3 Dimensions", img: "images/ovo3.webp", link: "g/OvO 3 Dimensions.html" },
  { name: "Paper.io 2", img: "images/paperio2.png", link: "g/Paperio2.html" },
  { name: "People Playground", img: "images/peopleplayground.jpg", link: "g/People Playground.html" },
  { name: "Pizza Tower", img: "images/pizza tower.png", link: "g/Pizza Tower.html" },
  { name: "Pokemon Emerald", img: "images/pokemon emerald.png", link: "g/Pokémon Emerald.html" },
  { name: "Pokemon Firered", img: "images/pokemon firered.png", link: "g/Pokémon Firered.html" },
  { name: "Pokemon Red", img: "images/pokemon red.png", link: "g/Pokémon Red.html" },
  { name: "Pou", img: "images/pou.webp", link: "g/Pou.html" },
  { name: "R.E.P.O.", img: "images/repo.webp", link: "g/R.E.P.O.html" },
  { name: "Raldis Crackhouse", img: "images/raldis crackhouse.png", link: "g/Raldis Crackhouse.html" },
  { name: "Rerun", img: "images/rerun.webp", link: "g/Rerun.html" },
  { name: "Run", img: "images/run1.webp", link: "g/Run 1.html" },
  { name: "Run 2", img: "images/run2.jpg", link: "g/Run 2.html" },
  { name: "Run 3", img: "images/run3.webp", link: "g/Run 3.html" },
  { name: "Sandtris", img: "images/sandtris.webp", link: "g/Sandtris.html" },
  { name: "Schoolboy Runaway", img: "images/schoolboyrunaway.webp", link: "g/Schoolboy Runaway.html" },
  { name: "Slither.io", img: "images/slitherio.webp", link: "g/Slither.io.html" },
  { name: "Slope", img: "images/slope.webp", link: "g/Slope.html" },
  { name: "Slope 2", img: "images/slope2.webp", link: "g/Slope 2.html" },
  { name: "Solar Smash", img: "images/solar smash.webp", link: "g/Solar Smash.html" },
  { name: "Sonic Mania", img: "images/sonic mania.png", link: "g/Sonic Mania.html" },
  { name: "Sonic.EXE (ORIGINAL)", img: "images/sonicexe.webp", link: "g/Sonic.EXE (ORIGINAL).html" },
  { name: "Soundboard", img: "images/redbutton.webp", link: "g/Soundboard.html" },
  { name: "Subway Surfers", img: "images/subwaysurfers.jpg", link: "g/Subway Surfers_ San Francisco.html" },
  { name: "Super Mario 64", img: "images/supermario 64.png", link: "g/Super Mario 64.html" },
  { name: "Super Mario Bros", img: "images/supermariobros.png", link: "g/Super Mario Bros.html" },
  { name: "Superhot", img: "images/superhot.png", link: "g/Superhot.html" },
  { name: "Survival Race", img: "images/survival race.webp", link: "g/Survival Race.html" },
  { name: "That's Not My Neighbor", img: "images/thatsnotmyneighbor.png", link: "g/That's Not My Neighbor.html" },
  { name: "The Impossible Quiz", img: "images/the impossible quiz.png", link: "g/The Impossible Quiz.html" },
  { name: "The man in the window", img: "images/the man in the window.png", link: "broken.html" },
  { name: "The Oregon Trail", img: "images/the oregon trail.png", link: "g/The Oregon Trail.html" },
  { name: "Ultrakill", img: "images/ultrakill.png", link: "g/Ultrakill.html" },
  { name: "Undertale", img: "images/undertale.webp", link: "g/Undertale.html" },
  { name: "Undertale Yellow", img: "images/undertale yellow.webp", link: "g/Undertale Yellow.html" },
  { name: "Web Fishing", img: "images/web fishing.png", link: "g/Web Fishing.html" },
  { name: "Wordle", img: "images/wordle.webp", link: "g/Wordle.html" },
  { name: "Worlds Hardest Game", img: "images/worldshardestgame.webp", link: "g/Worlds Hardest Game.html" },
];

export const apps = [
  { name: "Request A Game/App", img: "images/google forms.jpg", link: "g/Request.html" },
  { name: "Watch + Download Youtube Videos", img: "images/download.png", link: "g/cutyt.html" },
  { name: "EmulatorJS", img: "images/EmulatorJS.png", link: "g/emulator.html" },
];
